### ISSUE TITLE
make images responsive

### ISSUE THREAD

**Issue by nicholaskajoh** [Xzya/simple-hugo-theme#2]
Can we make images responsive-ish? Currently large images look like this...
![on making lagos a little saner _ alpha coder](https://user-images.githubusercontent.com/17048405/51079397-a2ab9400-16c6-11e9-881b-9dd17d76906c.jpg)
I'll be glad to send a PR.
Cheers!

**Comment by Xzya** [comment]
Hey,

You can achieve this with the following CSS:

```css
img {
    max-width: 100%;
    max-height: 100%;
    display: block;
    margin-left: auto;
    margin-right: auto;
}
```

I made a [new commit](https://github.com/Xzya/simple-hugo-theme/commit/f5be89e67a8058a0dc6772dd7332dfb5e97c2b63) with these changes.

Let me know if this fixes your problem,
Thanks!
